name: hack_gdg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::google-cloud-aiplatform
  - numpy
  - ipykernel
  - pip:
      - anyio==4.4.0
      - boto3==1.34.117
      - botocore==1.34.117
      - chevron==0.14.0
      - click==8.1.7
      - dataclasses-json==0.6.6
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.1.1
      - environs==9.5.0
      - faiss-cpu==1.8.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filelock==3.14.0
      - fsspec==2024.5.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.2.1
      - langchain-community==0.2.1
      - langchain-core==0.2.3
      - langchain-openai==0.1.8
      - langchain-text-splitters==0.2.0
      - langsmith==0.1.67
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.2
      - mdurl==0.1.2
      - milvus-lite==2.4.6
      - mypy-extensions==1.0.0
      - octoai-sdk==0.10.1
      - openai==1.30.5
      - orjson==3.10.3
      - pandas==2.2.2
      - pillow==10.3.0
      - pymilvus==2.4.3
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - rich==13.7.1
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soundfile==0.12.1
      - sqlalchemy==2.0.30
      - starlette==0.37.2
      - tenacity==8.3.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.41.2
      - typer==0.12.3
      - types-pyyaml==6.0.12.20240311
      - types-requests==2.32.0.20240523
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.30.0
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - websockets==12.0

